from __future__ import annotations

import copy
from typing import Any, Literal

BillingModel = Literal["prepaid", "postpaid", "free_tier", "unknown"]

INVENTORY_PROVIDERS: dict[str, dict[str, Any]] = {
    "openai": {
        "id": "openai",
        "name": "openai",
        "display_name": "OpenAI",
        "base_url": "https://api.openai.com/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "OPENAI_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "postpaid",
        "is_direct": True,
        "routing_note": None,
    },
    "anthropic": {
        "id": "anthropic",
        "name": "anthropic",
        "display_name": "Anthropic",
        "base_url": "https://api.anthropic.com/v1",
        "auth_type": "api_key",
        "auth_header": "x-api-key",
        "auth_prefix": "",
        "key_env_var": "ANTHROPIC_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "postpaid",
        "is_direct": True,
        "routing_note": None,
    },
    "openrouter": {
        "id": "openrouter",
        "name": "openrouter",
        "display_name": "OpenRouter",
        "base_url": "https://openrouter.ai/api/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "OPENROUTER_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": "/key",
        "billing_model": "prepaid",
        "is_direct": False,
        "routing_note": "Routes requests to multiple providers. Credits are OpenRouter-specific.",
    },
    "google": {
        "id": "google",
        "name": "google",
        "display_name": "Google AI (Gemini)",
        "base_url": "https://generativelanguage.googleapis.com/v1beta",
        "auth_type": "api_key",
        "auth_header": "x-goog-api-key",
        "auth_prefix": "",
        "key_env_var": "GOOGLE_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "free_tier",
        "is_direct": True,
        "routing_note": None,
    },
    "groq": {
        "id": "groq",
        "name": "groq",
        "display_name": "Groq",
        "base_url": "https://api.groq.com/openai/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "GROQ_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "free_tier",
        "is_direct": True,
        "routing_note": None,
    },
    "together": {
        "id": "together",
        "name": "together",
        "display_name": "Together AI",
        "base_url": "https://api.together.xyz/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "TOGETHER_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": None,
    },
    "perplexity": {
        "id": "perplexity",
        "name": "perplexity",
        "display_name": "Perplexity",
        "base_url": "https://api.perplexity.ai",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "PERPLEXITY_API_KEY",
        "models_endpoint": None,
        "health_check_endpoint": None,
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": None,
    },
    "cohere": {
        "id": "cohere",
        "name": "cohere",
        "display_name": "Cohere",
        "base_url": "https://api.cohere.com/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "COHERE_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "postpaid",
        "is_direct": True,
        "routing_note": None,
    },
    "mistral": {
        "id": "mistral",
        "name": "mistral",
        "display_name": "Mistral AI",
        "base_url": "https://api.mistral.ai/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "MISTRAL_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "postpaid",
        "is_direct": True,
        "routing_note": None,
    },
    "deepseek": {
        "id": "deepseek",
        "name": "deepseek",
        "display_name": "DeepSeek",
        "base_url": "https://api.deepseek.com/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "DEEPSEEK_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": "/user/balance",
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": None,
    },
    "xai": {
        "id": "xai",
        "name": "xai",
        "display_name": "xAI (Grok)",
        "base_url": "https://api.x.ai/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "XAI_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": None,
    },
    "huggingface": {
        "id": "huggingface",
        "name": "huggingface",
        "display_name": "Hugging Face",
        "base_url": "https://api-inference.huggingface.co",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "HF_API_KEY",
        "models_endpoint": None,
        "health_check_endpoint": None,
        "credit_check_endpoint": None,
        "billing_model": "free_tier",
        "is_direct": True,
        "routing_note": None,
    },
    "replicate": {
        "id": "replicate",
        "name": "replicate",
        "display_name": "Replicate",
        "base_url": "https://api.replicate.com/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "REPLICATE_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "postpaid",
        "is_direct": True,
        "routing_note": None,
    },
    "fireworks": {
        "id": "fireworks",
        "name": "fireworks",
        "display_name": "Fireworks AI",
        "base_url": "https://api.fireworks.ai/inference/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "FIREWORKS_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "postpaid",
        "is_direct": True,
        "routing_note": None,
    },
    "nvidia": {
        "id": "nvidia",
        "name": "nvidia",
        "display_name": "NVIDIA NIM",
        "base_url": "https://integrate.api.nvidia.com/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "NVIDIA_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "free_tier",
        "is_direct": True,
        "routing_note": None,
    },
    "moonshot": {
        "id": "moonshot",
        "name": "moonshot",
        "display_name": "Moonshot (Kimi)",
        "base_url": "https://api.moonshot.cn/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "MOONSHOT_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": "/users/me/balance",
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": None,
    },
    "dashscope": {
        "id": "dashscope",
        "name": "dashscope",
        "display_name": "DashScope (Qwen)",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "DASHSCOPE_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "postpaid",
        "is_direct": True,
        "routing_note": None,
    },
    "minimax": {
        "id": "minimax",
        "name": "minimax",
        "display_name": "MiniMax",
        "base_url": "https://api.minimaxi.com/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "MINIMAX_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "postpaid",
        "is_direct": True,
        "routing_note": (
            "OpenAI-compatible endpoint; if keys show invalid, re-add with the exact base URL "
            "via the custom field."
        ),
    },
    "siliconflow": {
        "id": "siliconflow",
        "name": "siliconflow",
        "display_name": "SiliconFlow",
        "base_url": "https://api.siliconflow.com/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "SILICONFLOW_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": None,
    },
    "stepfun": {
        "id": "stepfun",
        "name": "stepfun",
        "display_name": "StepFun",
        "base_url": "https://api.stepfun.com/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "STEPFUN_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": None,
    },
    "zhipu": {
        "id": "zhipu",
        "name": "zhipu",
        "display_name": "Zhipu AI (GLM / Z.ai)",
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "ZHIPU_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": "GLM models. Validated via a chat probe (no public model-list endpoint).",
    },
    "xiaomi": {
        "id": "xiaomi",
        "name": "xiaomi",
        "display_name": "Xiaomi MiMo",
        "base_url": "https://api.xiaomimimo.com/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "XIAOMI_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": (
            "Token-plan keys (tp- prefix). Regional endpoints: token-plan-cn.xiaomimimo.com, "
            "token-plan-sgp.xiaomimimo.com."
        ),
    },
    "tavily": {
        "id": "tavily",
        "name": "tavily",
        "display_name": "Tavily",
        "base_url": "https://api.tavily.com",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "TAVILY_API_KEY",
        "models_endpoint": None,
        "health_check_endpoint": None,
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": "Web search API. Keys start with tvly-.",
    },
    "firecrawl": {
        "id": "firecrawl",
        "name": "firecrawl",
        "display_name": "Firecrawl",
        "base_url": "https://api.firecrawl.dev",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "FIRECRAWL_API_KEY",
        "models_endpoint": None,
        "health_check_endpoint": None,
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": "Web scraping API. Keys start with fc-.",
    },
    "fal": {
        "id": "fal",
        "name": "fal",
        "display_name": "Fal.ai",
        "base_url": "https://api.fal.ai/v1",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Key",
        "key_env_var": "FAL_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "postpaid",
        "is_direct": True,
        "routing_note": "Generative media platform. Key format: UUID:hex.",
    },
    "exa": {
        "id": "exa",
        "name": "exa",
        "display_name": "Exa",
        "base_url": "https://api.exa.ai",
        "auth_type": "api_key",
        "auth_header": "x-api-key",
        "auth_prefix": "",
        "key_env_var": "EXA_API_KEY",
        "models_endpoint": None,
        "health_check_endpoint": None,
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": "Web search API. Key format: UUID.",
    },
    "brave-search": {
        "id": "brave-search",
        "name": "brave-search",
        "display_name": "Brave Search",
        "base_url": "https://api.search.brave.com/res/v1",
        "auth_type": "api_key",
        "auth_header": "X-Subscription-Token",
        "auth_prefix": "",
        "key_env_var": "BRAVE_SEARCH_API_KEY",
        "models_endpoint": None,
        "health_check_endpoint": None,
        "credit_check_endpoint": None,
        "billing_model": "prepaid",
        "is_direct": True,
        "routing_note": "Web search API. Keys start with BSA.",
    },
    "custom": {
        "id": "custom",
        "name": "custom",
        "display_name": "Custom Provider",
        "base_url": "",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": "CUSTOM_API_KEY",
        "models_endpoint": "/models",
        "health_check_endpoint": "/models",
        "credit_check_endpoint": None,
        "billing_model": "unknown",
        "is_direct": True,
        "routing_note": "Self-hosted / OpenAI-compatible endpoint (base URL supplied per key).",
    },
    "unidentified": {
        "id": "unidentified",
        "name": "unidentified",
        "display_name": "Unidentified (needs review)",
        "base_url": "",
        "auth_type": "api_key",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer",
        "key_env_var": None,
        "models_endpoint": None,
        "health_check_endpoint": None,
        "credit_check_endpoint": None,
        "billing_model": "unknown",
        "is_direct": True,
        "routing_note": (
            "Provider could not be auto-detected. Review the key and re-add with the correct "
            "provider or a custom base URL."
        ),
    },
}


def get_inventory_providers() -> dict[str, dict[str, Any]]:
    return copy.deepcopy(INVENTORY_PROVIDERS)


def get_inventory_provider(provider_id: str) -> dict[str, Any] | None:
    provider = INVENTORY_PROVIDERS.get(provider_id)
    if provider is None:
        return None
    return copy.deepcopy(provider)
